"""Resumable / checkpointed staged final generation (persistence repair only).

Proves the execution repair does NOT change the scientific design:

  1  completed architectures preserved unchanged by a later checkpoint
  2  one completed gated_deltanet chunk (a seed) can be persisted
  3  restart recognises that chunk (completed_cells / skip set)
  4  completed cells are skipped by run_grid
  5  missing cells ARE generated by run_grid
  6  no duplicate experimental cells are produced
  7  a simulated completed design reaches exactly 92,160 rows
  8  an interrupted write cannot corrupt the existing artifact
  9  conflicting / incompatible existing cells fail loudly
  10 an uninterrupted run is logically equivalent to a chunked one
  11 the frozen design / manifest are untouched
  12 gates + H1/H2/H3 analysis wait until all four architectures are complete

No GPU — run_grid's model + generation calls are stubbed.
`python -m unittest discover -s tests`.
"""

from __future__ import annotations

import contextlib
import io
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import pandas as pd

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_ROOT / "src"))

from ahnexp import config, dataset, evaluate, full_run, schema

_FCFG = config.final()
_ITEMS = dataset.generate_items(int(_FCFG["n_items"]), seed=int(_FCFG["seeds"][0]))
_ITEM_IDS = [it.item_id for it in _ITEMS]
_TARGETS = list(_FCFG["target_model_tat"])
_SEEDS = list(_FCFG["seeds"])
_ARMS = list(_FCFG["arms"])
_PER_SEED = len(_ITEM_IDS) * len(_TARGETS)          # 2880
_PER_ARM = _PER_SEED * len(_SEEDS)                  # 23040
_HAS_CALIB = (_ROOT / _FCFG["calibration_file"]).is_file()


def _rows(arch, seeds, *, items=None):
    """Synthetic schema-valid rows for the merge / progress helpers."""
    items = items if items is not None else _ITEM_IDS
    ft = {it.item_id: it.fact.fact_type for it in _ITEMS}
    dd = {it.item_id: it.distractor_density for it in _ITEMS}
    rows = []
    for s in seeds:
        for iid in items:
            for t in _TARGETS:
                rows.append({
                    "item_id": iid, "architecture": arch, "seed": int(s),
                    "fact_type": ft[iid], "distractor_density": dd[iid],
                    "target_position": "early",
                    "tokens_after_target": t - 55, "requested_tokens_after_target": t - 55,
                    "model_tokens_after_target": int(t),
                    "intended_model_tokens_after_target": int(t),
                    "target_fact_tokens": 12, "context_tokens": 200 + int(t),
                    "sliding_window": 256, "n_new_tokens": 2,
                    "correct": int(t < 256), "abstained": 0, "malformed": 0,
                    "answer_canonical": "x", "confidence": 0.7,
                    "prediction": "x", "gold": "x", "scorer_version": "1.0",
                })
    return schema.derive_boundary_conditions(
        schema.derive_memory_condition(pd.DataFrame(rows)), strict=True)


# --------------------------------------------------------------------------- #
# stubbed run_grid: no model, no GPU — trajectory build + scorer stay real
# --------------------------------------------------------------------------- #

class _Tok:
    def __call__(self, text, **_):
        return {"input_ids": text.split()}

    def __len__(self):
        return 50_000


def _fake_run_trial(model, tokenizer, trajectory):
    gold = trajectory["gold"]
    in_window = trajectory["model_tokens_after_target"] < 256
    return {"prediction": gold if in_window else "I don't know",
            "gold": gold, "confidence": 0.7, "n_new_tokens": 2}


def _run_grid(**kw):
    with mock.patch.object(evaluate, "run_trial", _fake_run_trial), \
         mock.patch.object(evaluate.models, "load", lambda *a, **k: (object(), _Tok())), \
         mock.patch.object(evaluate.models, "describe",
                           lambda name, *a, **k: {"arm": name, "sliding_window": 256}), \
         mock.patch.object(evaluate.models, "assert_matched", lambda *a, **k: None):
        return evaluate.run_grid(**kw)


_SMALL = _ITEMS[:6]                      # 6 items x 12 targets = 72 cells / seed
_PLAN = full_run.pressure_plan() if _HAS_CALIB else None


@unittest.skipUnless(_HAS_CALIB, "final_calibration.json not built")
class TestRunGridResume(unittest.TestCase):
    def setUp(self):
        self.dir = Path(tempfile.mkdtemp(prefix="ahn_resume_"))
        self.raw = self.dir / "results.parquet"

    def _generate(self, arms, seeds, skip=None, chunks=None):
        def cb(a, s, frame):
            if chunks is not None:
                chunks.append((a, s, 0 if frame is None else len(frame)))
            full_run.checkpoint_merge(frame, self.raw, architecture=a, seed=s, verbose=False)
        return _run_grid(items=_SMALL, tokenizer_for_items=None, ahn_repo=None, mode="full",
                         arms=arms, pressure_plan=_PLAN, seeds=seeds,
                         skip_cells=skip or set(), on_chunk=cb)

    def test_missing_cells_generated_and_checkpointed_per_seed(self):        # 5, 2, 6
        chunks = []
        df = self._generate(["gated_deltanet"], [0, 1], chunks=chunks)
        self.assertEqual(len(df), 72 * 2)
        self.assertEqual([c[:2] for c in chunks],
                         [("gated_deltanet", 0), ("gated_deltanet", 1)])
        art = pd.read_parquet(self.raw)
        self.assertEqual(len(art), 72 * 2)
        self.assertFalse(art.duplicated(subset=full_run.CELL_KEY).any())

    def test_restart_recognises_chunk_and_skips_completed_cells(self):        # 3, 4
        self._generate(["gated_deltanet"], [0])
        done = full_run.completed_cells(self.raw)
        self.assertEqual(len(done), 72)
        self.assertTrue(all(c[0] == "gated_deltanet" and c[2] == 0 for c in done))

        chunks = []
        df2 = self._generate(["gated_deltanet"], [0, 1],
                             skip={c for c in done if c[0] == "gated_deltanet"}, chunks=chunks)
        self.assertEqual(len(df2), 72)                     # only seed 1 regenerated
        self.assertEqual(chunks[0][2], 0)                  # seed 0: every cell skipped
        self.assertEqual(chunks[1][2], 72)
        art = pd.read_parquet(self.raw)
        self.assertEqual(len(art), 144)
        self.assertFalse(art.duplicated(subset=full_run.CELL_KEY).any())

    def test_partial_seed_resume_fills_only_missing_cells(self):
        half = _rows("gated_deltanet", [0], items=_ITEM_IDS[:3])
        full_run.checkpoint_merge(half, self.raw, architecture="gated_deltanet", seed=0, verbose=False)
        df = self._generate(["gated_deltanet"], [0], skip=full_run.completed_cells(self.raw))
        self.assertEqual(len(df), 3 * 12)                  # 3 missing items only
        art = pd.read_parquet(self.raw)
        self.assertEqual(len(art), 72)
        self.assertFalse(art.duplicated(subset=full_run.CELL_KEY).any())

    def test_uninterrupted_equals_chunked(self):                             # 10
        self._generate(["gated_deltanet"], [0, 1, 2])
        one = _run_grid(items=_SMALL, tokenizer_for_items=None, ahn_repo=None, mode="full",
                        arms=["gated_deltanet"], pressure_plan=_PLAN, seeds=[0, 1, 2])
        b = self.dir / "one.parquet"
        one.to_parquet(b, index=False)
        cols = full_run.CELL_KEY + ["correct", "abstained", "malformed", "prediction",
                                    "confidence", "model_tokens_after_target"]
        ca = pd.read_parquet(self.raw).sort_values(full_run.CELL_KEY).reset_index(drop=True)[cols]
        cb = pd.read_parquet(b).sort_values(full_run.CELL_KEY).reset_index(drop=True)[cols]
        pd.testing.assert_frame_equal(ca, cb)


class TestCheckpointMerge(unittest.TestCase):
    def setUp(self):
        self.raw = Path(tempfile.mkdtemp(prefix="ahn_ck_")) / "results.parquet"

    def test_completed_architectures_preserved_by_a_later_checkpoint(self):  # 1
        base = pd.concat([_rows(a, _SEEDS) for a in ("transformer", "mamba2", "deltanet")],
                         ignore_index=True)
        base.to_parquet(self.raw, index=False)
        before = pd.read_parquet(self.raw).sort_values(full_run.CELL_KEY).reset_index(drop=True)
        merged = full_run.checkpoint_merge(_rows("gated_deltanet", [0]), self.raw,
                                           architecture="gated_deltanet", seed=0, verbose=False)
        keep = (merged[merged["architecture"] != "gated_deltanet"]
                .sort_values(full_run.CELL_KEY).reset_index(drop=True))
        pd.testing.assert_frame_equal(keep[before.columns], before[before.columns])
        self.assertEqual(len(merged), 3 * _PER_ARM + _PER_SEED)

    def test_simulated_completed_design_is_exactly_92160(self):              # 7
        for arm in _ARMS:
            full_run.checkpoint_merge(_rows(arm, _SEEDS), self.raw, architecture=arm, verbose=False)
        art = pd.read_parquet(self.raw)
        self.assertEqual(len(art), 92_160)
        self.assertFalse(art.duplicated(subset=full_run.CELL_KEY).any())
        prog = full_run.design_progress(art)
        self.assertTrue(prog["complete"])
        self.assertEqual(prog["total_cells"], 92_160)
        full_run.assert_compatible_with_frozen_design(art, allow_incomplete=False)

    def test_identical_duplicate_collapsed(self):                            # 6
        rows = _rows("gated_deltanet", [0])
        full_run.checkpoint_merge(rows, self.raw, architecture="gated_deltanet", verbose=False)
        merged = full_run.checkpoint_merge(rows.copy(), self.raw,
                                           architecture="gated_deltanet", verbose=False)
        self.assertEqual(len(merged), _PER_SEED)

    def test_conflicting_duplicate_cell_fails_loudly(self):                  # 9
        rows = _rows("gated_deltanet", [0])
        full_run.checkpoint_merge(rows, self.raw, architecture="gated_deltanet", verbose=False)
        clash = rows.copy()
        clash.loc[clash.index[0], "correct"] = 1 - int(clash.loc[clash.index[0], "correct"])
        with self.assertRaises(SystemExit) as e:
            full_run.checkpoint_merge(clash, self.raw, architecture="gated_deltanet", verbose=False)
        self.assertIn("CONFLICTING DUPLICATE", str(e.exception))

    def test_incompatible_existing_cells_fail_loudly(self):                  # 9
        bad = _rows("gated_deltanet", [0])
        bad["seed"] = 99
        with self.assertRaises(SystemExit) as e:
            full_run.checkpoint_merge(bad, self.raw, architecture="gated_deltanet", verbose=False)
        self.assertIn("unknown seeds", str(e.exception))

    def test_column_mismatch_with_existing_artifact_fails_loudly(self):      # 9
        _rows("gated_deltanet", [0]).drop(columns=["confidence"]).to_parquet(self.raw, index=False)
        with self.assertRaises(SystemExit) as e:
            full_run.checkpoint_merge(_rows("mamba2", [0]), self.raw,
                                      architecture="mamba2", verbose=False)
        self.assertIn("COLUMN MISMATCH", str(e.exception))

    def test_interrupted_write_cannot_corrupt_the_artifact(self):            # 8
        _rows("transformer", _SEEDS).to_parquet(self.raw, index=False)
        before = self.raw.read_bytes()

        def boom(src, dst):
            Path(src).unlink(missing_ok=True)
            raise KeyboardInterrupt

        with mock.patch("os.replace", boom):
            with self.assertRaises(KeyboardInterrupt):
                full_run.checkpoint_merge(_rows("gated_deltanet", [0]), self.raw,
                                          architecture="gated_deltanet", verbose=False)
        self.assertEqual(self.raw.read_bytes(), before)
        self.assertFalse(self.raw.with_name(self.raw.name + ".tmp").exists())

    def test_checkpoint_message_is_explicit(self):                           # 2
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            full_run.checkpoint_merge(_rows("gated_deltanet", [0, 1, 2]), self.raw,
                                      architecture="gated_deltanet", seed=2, verbose=True)
        out = buf.getvalue()
        self.assertIn("CHECKPOINT SAVED", out)
        self.assertIn("gated_deltanet completed seeds: [0, 1, 2]", out)
        self.assertIn(f"gated_deltanet rows: {3 * _PER_SEED} / {_PER_ARM}", out)
        self.assertIn(f"total rows: {3 * _PER_SEED} / 92160", out)


class TestAnalysisGatingAndFrozenDesign(unittest.TestCase):
    def setUp(self):
        self.raw = Path(tempfile.mkdtemp(prefix="ahn_gate_")) / "results.parquet"

    def test_analysis_waits_until_all_four_arms_complete(self):              # 12
        for arm in ("transformer", "mamba2", "deltanet"):
            full_run.checkpoint_merge(_rows(arm, _SEEDS), self.raw, architecture=arm, verbose=False)
        self.assertFalse(full_run.design_progress(pd.read_parquet(self.raw))["complete"])
        full_run.checkpoint_merge(_rows("gated_deltanet", _SEEDS), self.raw,
                                  architecture="gated_deltanet", verbose=False)
        self.assertTrue(full_run.design_progress(pd.read_parquet(self.raw))["complete"])

    def test_run_full_script_defers_analysis_on_a_staged_artifact(self):     # 12
        src = (_ROOT / "scripts" / "run_full.py").read_text()
        self.assertIn("analysis deferred", src)
        self.assertIn("design_progress", src)
        self.assertIn('if not prog["complete"]:', src)
        self.assertIn("_analyse_and_gate(root, merged", src)

    def test_frozen_manifest_and_design_untouched(self):                     # 11
        m = config.final_manifest()
        self.assertEqual(m["expected_generations"], 92_160)
        self.assertEqual(m["prompt_sha256"], config.prompt_hash())
        self.assertEqual(m["calibration_sha256"],
                         config.file_sha256(config.final()["calibration_file"]))
        self.assertEqual(config.final()["target_model_tat"], _TARGETS)
        self.assertEqual(config.final()["seeds"], _SEEDS)
        self.assertEqual(config.final()["n_items"], 240)


if __name__ == "__main__":
    unittest.main(verbosity=2)
